POST / HTTP/1.1
Content-Type: application/json;charset=UTF-8
User-Agent: Java/1.8.0_101
Host: 5b7a165b.ngrok.io
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Content-Length: 667
X-Forwarded-Proto: https
X-Forwarded-For: 52.1.216.138

{"name":"copper-nova-develop","url":"job/copper-nova-develop/","build":{"full_url":"http://jenkins-internal.blueprintsys.net:8080/job/copper-nova-develop/3865/","number":3865,"queue_id":18010,"phase":"STARTED","url":"job/copper-nova-develop/3865/","scm":{"url":"git@github.com:BlueprintSys/blueprint.git","branch":"blueprint/develop","commit":"1c76a9bd0570ca5eef4cf8ce4c496df52abd0a8b"},"parameters":{"BP_Major_Version":"2","BP_Release_Version":"0","BuildNovaWebApplication":"true","BranchToBuild":"develop","BuildRaptorSolution":"true","BuildNovaServices":"true","BP_Minor_Version":"0","BuildDataAnalytics":"false","GetCodeCoverage":"true"},"log":"","artifacts":{}}}